### ISSUE TITLE
vertices and indices out param support

### ISSUE THREAD

**Issue by whiterabbit42k** [w1th0utnam3/splashsurf#4]
So my usecase is currently a semi-realtime meshing of fluids from salva; for around 1k particles, I'm able to mesh about every 30-60ms.

As apart of perf investigations, I'm wondering if we can reduce some of this overhead by providing a vertices and indices out param, perhaps something like:

```rust
splashsurf_lib::reconstruct_surface_with(&positions, &params, &mut vertices, &mut indices)
```

This should reduce some pressure on the allocator?

**Comment by w1th0utnam3** [comment]
So your idea would be to basically call `.clear()` on them and just reuse the reserved capacity? Maybe you can try it out to see how this affects performance in your case. I would be open to merge it.

**Comment by whiterabbit42k** [comment]
I have a patch doing this which does not change the current api; i can push it. Yea so with out params like that the idea is that you only get the allocation hit once or twice so memory use becomes stable after running for a while (it keeps writing into same heap storage)

**Comment by whiterabbit42k** [comment]
done in #7
