### ISSUE TITLE
optional vtkio dependency

### ISSUE THREAD

**Issue by whiterabbit42k** [w1th0utnam3/splashsurf#5]
Wondering the work to make this vtkio dependency optional? I do not use any file formats for meshing, but directly pass in-memory points that salva generates, so the `vtkio` dep here brings in unncessary stuff.

Would you be open to PR making this optional?

**Comment by w1th0utnam3** [comment]
Right, that would make sense. Should be fairly easy, we just have to enable this by default in the CLI then. Maybe we should also consider moving the profiling behind a flag.

**Comment by whiterabbit42k** [comment]
i looked into this only usage appears to be the IOBuffer; wasn't quite clear to me what that does? Would you be open to adding a feature flag and cfg-ing the import and usage?

**Comment by w1th0utnam3** [comment]
Yeah, all VTK stuff is related to convenience functions to convert the meshes into VTK data structures (mostly for the CLI).

Just implemented and pushed this (https://github.com/w1th0utnam3/splashsurf/commit/183265bfcc4ba75a7f153d29788786c66d562271). Maybe you can try it out, then I'll close the issue.

**Comment by whiterabbit42k** [comment]
tested, works perfectly :) thank you!

**Comment by w1th0utnam3** [comment]
The profiling stuff is also optional now.
