### ISSUE TITLE
crates release of splashsurf_lib to match salva 0.7

### ISSUE THREAD

**Issue by whiterabbit42k** [w1th0utnam3/splashsurf#57]
salva 0.7 uses nalgebra 0.29; it would be great if we had a matching crates.io release of splashsurf_lib so the nalgebra crate can be unified.

I see splashsurf_lib already uses 0.29 in master Cargo.toml; is it possible to get a 0.8 release with nalgebra 0.29 so we can have match for salva?

Thanks!

**Comment by w1th0utnam3** [comment]
Right, the latest changes have been sitting here for quite some time. I just published a new release.

**Comment by whiterabbit42k** [comment]
wow thanks for such a fast release!
